name: Build Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore workloads
        run: dotnet workload restore

      - name: Install MAUI Android workload
        run: dotnet workload install maui-android --yes

      - name: Restore NuGet packages
        run: dotnet restore src/MyMauiApp/MyMauiApp.csproj

      - name: Build Android
        run: dotnet build src/MyMauiApp/MyMauiApp.csproj -c Release -f net8.0-android --no-restore